export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';

export const STORY_SET_URL = 'STORY_SET_URL';
export const STORY_SET_CAPTION = 'STORY_SET_CAPTION';
export const STORY_SET_NEW_CAPTION = 'STORY_SET_NEW_CAPTION';
export const STORY_SET_SELECTION_TYPE = 'STORY_SET_SELECTION_TYPE';

